### ISSUE TITLE
Review director requirements and refactor as required

### ISSUE THREAD

**Issue by collinsfoobar** [besasm/EMGAATS#113]
Our current modeling practice requires us to calculate the peak HGL at the location where a building's  sewer lateral connects to the pipe.  Basement flooding risk is a determined based on a comparison of peak HGL and basement floor.  The model gives peak HGL at manholes. 

The HGL at the lateral connection to pipe is calculated using the fract2sewbeg property.   The frac2sewbeg property is a fraction calculated as the lateral connection distance from the upstream node divided by the total pipe length.

__Questions__
1. The 'assumekey' field was used to track the assumption behind the director.
What are the requirements to track the assumptions the director represents in the current system?
2. Review the 100 percent requirement.
3. Should Storm and Sanitary directors be separate classes? __[NO]__
4. Should areas be included in the network if no directors link them to the network?

__Summary of Director Requirements and Behavior__

__All Directors__
Are associated with an area.
If an area is selected all directors associated with the area are included in the network.
Can be assigned only one of the following: ToLink, ToNode, Infiltration.
Operate on an area's property AreaSqFt (storm) or SanitaryFlowCfs (sanitary)
Directors Must Add to 100 percent of the area's property.
Directors are initialized as type storm with AreaSqFt == 0, SanitaryFlowCfs = 0, Frac2SewBeg = 0
=>Once these are set the type should not change.

__Storm Directors__
Operate on Area.AreaSqFt 
Not used to calculate basement flooding risk.
frac2sewbeg not required

__Sanitary Directors__
Operate on Area.SanitaryFlowCfs
Used to calculate basement flooding risk.
- frac2sewbeg required
- If more than one sanitary director is assigned from one object, the worst case HGL will govern.
- If the sanitary director is assigned to the node, the fract2sewbeg = 0

**Comment by arnelmandilag** [comment]
Property is probably best attached to the Director, not an Area.

**Comment by collinsfoobar** [comment]
_Based on the decision below I thought that the director type was not required and that sanitary flow rate and inflow node would be set on the building area._
__20150114 Design Session__
Sanitary Directors
__DECISION:__ We will not be using directors to develop sanitary flows Area objects will have a node that directs sanitary inflow.
Two additional fields for each area are required: sanitary_flow_cfs and sanitary_node

**Comment by arnelmandilag** [comment]
Options: do the above recommendation or use Director objects and have multiple sanitary directors. Sanitary directors will report basement backup risk. Multiple directors will resolve to the worst BSBR. Director will need Frac2SwrBeg and ToLink.

**Comment by collinsfoobar** [comment]
CloneDirector(INetwork subnetwork, IDirector director)

cloning directors to infliltration
cloning directors to nodes / links outside of the network
