### ISSUE TITLE
Add link_symbology and node_symbology field to the data objects and business classes

### ISSUE THREAD

**Issue by collinsfoobar** [besasm/EMGAATS#117]
Kristi says everyone should have the same symbology.

Rough standard for pipes;
Combined: magenta
Sanitary: red
Storm: green

__DECISION:__
1. Use existing values in LinkType as values Link_Symbology field.  
2. Symbolize nodes base on Node_Symbology
3. Use existing Master node type symbology

__ACTION__
Add link_symbology and node_symbology field to the data objects and corresponding properties to the business classes for links and nodes.

SEE #147

**Comment by arnelmandilag** [comment]
Rough standard:

- Combined: magenta
- Sanitary: red
- Storm: green
