### ISSUE TITLE
Eliminate spatial component of directors.

### ISSUE THREAD

**Issue by collinsfoobar** [besasm/EMGAATS#120]
__Logic__
Directors are always associated with an single area.
Directors have no meaning outside of an area.

__Consequence:__
(-) cannot do spatial query to link building to director but this is probably not important
_(+)This fits in with Jana's comment about her preferred editing method_
(+) decreased load times, maybe
(+) less clutter on map
(+) less complicated

Grid control for managing Area/Directors

**Comment by arnelmandilag** [comment]
I think the key here is the affordance of spatial queries not being important. There's no reason why the tools we develop can't be spatial in nature, but that tool does not have to result in a spatial feature being created (similar to the current tool).

I'm not sure this would be any less clutter (such a layer can always be turned off), but it would definitely be less complicated in that we wouldn't need to do any "separation" logic to ensure that Directors don't sit on top of each other.

**Comment by ahedhi** [comment]
We have already eliminated the spatial query for this. This was to speed the load time. Directors now have area_id and node_id fields for their topology. The only thing I was considering was that we would continue to use the spatial relationship when a user added a Director, they would click in an Area and the area_id would be automatically populated based on the location. There might also be a validation rule to ensure Directors are within their area.

The one positive I can see with keeping the Directors as points is that you could potentially place them in the general location on a large roof (for example) where a particular downspout or other connection is located. I'm not sure if this would be important to the users.

**Comment by arnelmandilag** [comment]
Definitely ask the users about that last bit regarding placing directors specifically in spots representing things like downspouts, etc. I'm pretty sure they don't track that now, and they would look to the modelers to see if they will ever need to.
