### ISSUE TITLE
Implement multi-user database editing.

### ISSUE THREAD

**Issue by arnelmandilag** [besasm/EMGAATS#122]
Use ArcGIS functionality as much as possible. History functionality could handle our archiving problem. Depends on #107.

**Comment by ahedhi** [comment]
Generally no code changes are apparently needed.

Added #155 to address a specific issue discovered during testing. Any additional issues discovered should be added as separate items.

**Comment by arnelmandilag** [comment]
Although no code changes are needed, what specific steps are required to enable this? Is registering the dataset as "versioned without the option to move edits to base" all that's needed?

**Comment by ahedhi** [comment]
You need to register each feature class dataset, stand alone feature class (we don't have any of these at the moment) and tables as versioned "without the option to move edits to base" _and_ "Enable Archiving". Both of these can be done manually by right-clicking the item in ArcCatalog and going to the "Manage" sub-menu. I have also included these steps in the upload script I prepared for the initial data conversion.
