### ISSUE TITLE
Review entity name properties and refactor as required

### ISSUE THREAD

**Issue by ahedhi** [besasm/EMGAATS#129]
Currently, all entities have a name property except for Areas and Directors. I think it would make sense for these two to have a name. On the other hand, Infiltrators and Storages don't need names because they are always associated with a particular node in a one-to-one relationship. There is no need to distinguish these, except by what node they are associated with.

__User Input__
Review Table below and comment

**Comment by collinsfoobar** [comment]
![image](https://cloud.githubusercontent.com/assets/12415719/8214442/1b31dee6-14de-11e5-8666-ec913f9064a7.png)

**Comment by collinsfoobar** [comment]
As a general statement, names are strings that allow alphanumeric characters.

Currently we have one exception to this, the link_name (formerly known as the MlinkID).  The link_name currently is a number. Based on feedback from Kristi, MlinkID and AreaID will be integers

**Comment by collinsfoobar** [comment]
remove name fields from storage and infiltrator (business class, UI, schema.)
check director

**Comment by collinsfoobar** [comment]
done as part of feature/schema_update
