### ISSUE TITLE
Create import command to transfer links from DME

### ISSUE THREAD

**Issue by ahedhi** [besasm/EMGAATS#136]
Copy/Paste will not work because it does not transfer all attributes or nodes.

Link to #139, #73

We could potentially use the existing code from Besasm.Emgaats.Maintenance

__Options__
1. User edits add/delete tables. DME import creates and maintains add and delete tables
2. User edits a network. Tool creates local copy of database and add/delete tables are created from the changes

__User Input (Aug 25 2015):__  
Do not like the tables.  Prefer option 2.
Review process

__Process__
Create local copy of master (model)
Apply DME Links
Create Diff Tables
Merge into master

**Comment by collinsfoobar** [comment]
Options
1. User edits add/delete tables.  DME import creates and maintains add and delete tables
2. User edits a network.  Tool creates local copy of database and add/delete tables are created from the changes

**Comment by arnelmandilag** [comment]
Ready for testing

**Comment by ahedhi** [comment]
Done
