### ISSUE TITLE
Applying Diff Tables 

### ISSUE THREAD

**Issue by collinsfoobar** [besasm/EMGAATS#139]
Link to #136 #73
\\\\besfile1\modeling\Modeling_Framework\EMD\EMD083.doc

__Applies to:__
Alternatives that are going to construction.
DME updates
Have a way for modelers to push model changes to technicians for incorporation into Master Data.

__USER INPUT__ 
Discuss workflow for copying elements in change tables from one model to another. 

If an entity to be updated is deleted in the target database, notify the user but do not add the entity

__Core Team Discussion__
What are the implications of users manually editing these tables?
->Duplicate names will be caught on validation.

__Entity Identification__
When applying changes in a long transaction (with diff tables) we need to determine which entity in the original table is to be changed/deleted. Entity names will used to do this.  For unnamed entities, the primary associated named entity will be used.

In schema named entities will be identified by the caption property of the entity field that is the name.  e.g. areas.area_name caption = 'isname'

For unnamed entities, the primary associated named entity will be identified by the caption property of the foreign key field of the primary entity that is named.  e.g. directors.area_id caption = 'isowner'.

For purposes of applying the diff tables, unnamed entities can be thought of as fields of the named entities.  If the unnamed entity is changed, all of the entities associated with the primary named entity will be updated.  e.g.  if a director is changed, the area associated with the director and all other directors associated with the area will be updated.

![emgaatsclassnames](https://cloud.githubusercontent.com/assets/12415719/10178267/906bd2bc-66b3-11e5-90bd-8d177095ece4.jpg)

__Applying Related Entities/Data__
For purposes of applying changes, if a "primary" entity is touched, all sub-entities and data from the source model will over-write the corresponding data in the target database. "Prime" entities are:

Nodes (sub entities: weirs, orifices, pumps, pump data, storage, storage data, infiltrator)
Links (as builts)
Areas (directors)
Cross Sections (cross section data)

**Comment by collinsfoobar** [comment]
Can you do a diff between alternative and a base model that is newer than the base model that was used to create the alternative?

Change detection or record changes.

**Comment by ahedhi** [comment]
Done. (With one major issue added separately: #194)
