### ISSUE TITLE
Create Director Grid Control

### ISSUE THREAD

**Issue by collinsfoobar** [besasm/EMGAATS#166]
__ISSUES__
directors to nowhere when 

related #192 

__CORE TEAM DISCUSSION__
__discussion item:__ consistency between primary entities (area, node, link)
_current status:_
all changes to directors are committed at time of area commit
changes to existing node decorations can be committed independently of the node commit.
_decision:_
leave as is until we have to fix it

__USER INPUT__

demonstrate

__USER INPUT HISTORY__

Eliminate existing director dialog

Functionality
Add 
Modify
Delete
Verify 100% accounted for

Grid shows either sanitary or storm not both
Edit in square feet
Percent edit not required.

fract2sewbeg enter using graphics
single column for destination type (N/P/I)
san storm radio button default storm

__USER INPUT REQUIRED__
storyboard control

**Comment by ahedhi** [comment]
![img_4485](https://cloud.githubusercontent.com/assets/11524991/11353908/33a7dc3c-91fc-11e5-9ace-19f9a792cf43.JPG)
