### ISSUE TITLE
Schema Changes

### ISSUE THREAD

**Issue by collinsfoobar** [besasm/EMGAATS#192]
__Area__
See #179 for schema changes

__________

__CORE TEAM DISCUSSION__
Before schema change we need to define how will these fields be used.
For example, subcatchments are currently built based solely on area type.  Whitaker requested ineffective disco to street to be included in separate catchment.  The current source field has this data.  Does this mean the description field would be used for this purpose.  I don't think we need to create catchments base on all source.

__USER INPUT__
__Director__
"code" field for director description (3 character -- to be fixed domain)
"source" field for information source (12 characters to start? -- to be fixed domain)

______________
__Cross Section__
See #149 for schema changes

___________________
__Node__
Remove "NodeType"
See #184 and #137

**Comment by ahedhi** [comment]
Done (on development branch)
