### ISSUE TITLE
UI update exception for DetectChangesButton causing subsequent menu buttons to disappear

### ISSUE THREAD

**Issue by arnelmandilag** [besasm/EMGAATS#196]
Arnold: I need you to check a fix I introduced to the develop branch at commit dd5c79283413f53a8554527856420d4aa4dab0f1 affecting the DetectChangesButton.OnUpdate() function. ArcMap was swallowing a null reference exception when accessing EmgaatsEditorExtension.Instance and keeping subsequent button/tool/menu OnUpdate() functions from firing (and hence those menu entries were disappearing after a model/master data was loaded). I wasn’t sure if I met your intention or whether we need to ensure further up that EmgaatsEditorExtension.Instance has been initialized.

**Comment by ahedhi** [comment]
Looks ok, though I'm curious why the extension is not loaded when it first runs. I'll look into it.

**Comment by collinsfoobar** [comment]
arnold says everything is fine
