### ISSUE TITLE
Test Simulation and Storm UI prior to user release

### ISSUE THREAD

**Issue by collinsfoobar** [besasm/EMGAATS#199]
Odd flashy behavior
Can't delete simulations

dates max at 12 hours - use 24 hour clock?

__________________________
test data folder
V:\9ESEN0000008\EMGAATS\TestDataActive\SellwoodModelFolder

**Comment by arnelmandilag** [comment]
Yeah, I know the deletes don't work (yet) and I need to provide some default values to prevent the flashing.
