### ISSUE TITLE
Can a ditch or pipe lose water in XP-SWMM?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [besasm/EMGAATS#21]
```
Answering this question can answer how we implement a Conveyor. We're currently 
questioning whether this is necessary in this version.
```

Original issue reported on code.google.com by `ArnelMan...@gmail.com` on 14 Nov 2014 at 5:09

**Comment by arnelmandilag** [comment]
This is considered obsolete in this version, as we're not supporting a Conveyor implementation in this round. We'll wait for further information from Stormwater System Plan.
