### ISSUE TITLE
Error when editing in Master links- "The number of points is less than required for feature"

### ISSUE THREAD

**Issue by yarrowm** [besasm/EMGAATS#226]
Trying to move pipe ds node (from ACF629 to ANJ544). The globalID matches that of the DME piipe currently connected at ANJ544. Also get this error when just trying to adjust location of DS node (rather than replace node). Get the following error:
![image](https://cloud.githubusercontent.com/assets/16343206/12069540/eda0bff2-afeb-11e5-94c5-e5e131ca5e96.png)

**Comment by arnelmandilag** [comment]
Likely related to #227.

**Comment by ahedhi** [comment]
These errors (together with #227) appear to be an issue with ArcSDE. I'm still investigating, but if you copy over the layer in ArcCatalog onto the SDE with no registration or archiving, these errors don't appear until you edit something. Then they do.

**Comment by yarrowm** [comment]
Is this supposed to be fixed? I tested it and it is still doing the same thing.

**Comment by ahedhi** [comment]
It is fixed, but I have not pushed the code out to users, yet. I will probably do so Monday and will then assign this issue to you. Once you verify it, you can close this issue.

**Comment by yarrowm** [comment]
Seems to be fixed.
