### ISSUE TITLE
Error when editing in Master links- "The specified part offset is invalid" 

### ISSUE THREAD

**Issue by yarrowm** [besasm/EMGAATS#227]
This error occurs when trying to use edit tool to adjust location of end of pipe. Still occurs after having saved changes to node location. 
![image](https://cloud.githubusercontent.com/assets/16343206/12069549/903f95bc-afec-11e5-990d-6cd28d258ce8.png)

**Comment by yarrowm** [comment]
I can sometimes make very small adjustments to the locations of pipes without this error.

**Comment by yarrowm** [comment]
Is this supposed to be fixed? I tested and could not replicate after many pipe adjustments. Did still get this error when adjusting streamline into APD831.

**Comment by arnelmandilag** [comment]
@ahedhi: is Yarrow supposed to re-test (maybe implied by your re-assignment)?

**Comment by arnelmandilag** [comment]
Crap! Removed Yarrow's comment by mistake (just prior to Arnold's fixes just above, on 1/14), which was:

Is this supposed to be fixed? I tested and could not replicate after many pipe adjustments. Did still get this error when adjusting streamline into APD831.

**Comment by ahedhi** [comment]
Yes, see my latest email. Users should verify fixes and close the issue, or reassign back to the developers.

**Comment by yarrowm** [comment]
Seems to be resolved as I cannot reproduce it.
