### ISSUE TITLE
EMGAATS selection tool sensitivity

### ISSUE THREAD

**Issue by yarrowm** [besasm/EMGAATS#228]
When there are many links over a small street area, it can be difficult to make the tool select the area with the pipes on. At 1:600 tool picks pipe from 5 feet away. Can the sensitivity be adjusted, or is there a keyboard shortcut work-around?

pick closest feature instead of first feature.

**Comment by arnelmandilag** [comment]
The current workaround is to zoom in to the area in question...but are you saying even at close zooms, the tool is still too jittery in its candidate selection?

**Comment by ahedhi** [comment]
Which tool are we talking about? In the case of the Entity Property Tool (the tool that opens the property dialogs), and the Flow Destination Tool (used to select the destination for directors and entities like weirs, orifices, and pumps), the code currently uses the snapping tolerance set in ArcMap: Editor Toolbar->Editor menu->Snapping->Options...

So, you can set this to whatever you like. Let me know (here) if this is adequate. Both these tools prioritize the top most visible entity layer. It also picks the first entity it finds within the snapping distance, even if it is not necessarily the closest. (This was done for performance reasons, but I could change it to snap to the closest.)

**Comment by yarrowm** [comment]
It's helpful to know how the selection is controlled.

**Comment by arnelmandilag** [comment]
Possibly an enhancement will be to allow the user to select from a list if many entities are pickable.

**Comment by ahedhi** [comment]
Now picks closest entity within the snap distance in the top most visible entity layer.
