### ISSUE TITLE
Enhance Node property editor to incorporate adding inflow control elements

### ISSUE THREAD

**Issue by arnelmandilag** [besasm/EMGAATS#75]
On 20150407, the team discussed how to add inflow controls. Because inflow controls are always node-based, Arnel proposed that we enhance the Node property editor to include inflow control elements. This could be a list box of elements (limited to one storage and one infiltrator at most, and any number of outgoing weirs, orifices, pumps, and pipes). Selecting an item from that list box opens up the appropriate properties related to that item. This could entail separating out the editors for weirs, orifices, pumps, and pipes into common classes that are used for the stand-alone editors for those types as well the node property editor.

**Comment by ahedhi** [comment]
Done.
