### ISSUE TITLE
Develop add/move node tool

### ISSUE THREAD

**Issue by arnelmandilag** [besasm/EMGAATS#82]
Allows dropping of nodes onto model or master "canvas." Opens node property edit window.

Rules:
Do not automatically delete orphaned nodes after link deletion.
During an edit session, allow nodes to be deleted without deleting connected links.
Do not allow saving of links without nodes.
Allow orphan nodes to be saved.
Delete decorations when a node is deleted during edit session.

**Comment by ahedhi** [comment]
Initial implementation complete.

Todo:

* When node edited, refresh entity
* When node is deleted, remove entity from Network

**Comment by collinsfoobar** [comment]
Rules:
Do not automatically delete orphaned nodes after link deletion.
During an edit session, allow nodes to be deleted without deleting connected links.
Do not allow saving of links without nodes.
Allow orphan nodes to be saved.

**Comment by ahedhi** [comment]
Done
