### ISSUE TITLE
Develop add/move link tool

### ISSUE THREAD

**Issue by arnelmandilag** [besasm/EMGAATS#83]
Allows click/click or click/drag of links between nodes, or if nodes aren't within a certain threshold, adds the necessary nodes first and adds the link in between. Opens up the link property editor. May also include capability to split existing links.

Auto generate link name.

Make sure this allows import from DME - See issue 112

**Comment by collinsfoobar** [comment]
__Typical Process Overview:__

1. Add links or import selected links from selection of DME or shape file
2. Add nodes.
3. Add node decorations

__Behavior based on user feedback__

Rules:
Do not automatically deleted orphaned nodes after link deletion.
During an edit session, allow nodes to be deleted without deleting connected links.
Do not allow saving of links without nodes.

**Comment by ahedhi** [comment]
Question: Should link_name (also area_name) be max + 1? For models? For master data? Or should these be unique at least relative to master data?

**Comment by ahedhi** [comment]
Done
