### ISSUE TITLE
Change exceptions in CrossSection to validations

### ISSUE THREAD

**Issue by arnelmandilag** [besasm/EMGAATS#84]
There still remain a few exceptions in this class (GetAreaSqIn, AddRatio) that should be re-evaluated to see if validations work better.

**Comment by ahedhi** [comment]
It makes sense to keep the exceptions in `GetAreaSqIn()` as this does not change the state of the object and these checks are necessary to get a valid return value. For `AddRatio()`, however, we could probably accept invalid data and validate later. This *does* change the state of the object.

**Comment by arnelmandilag** [comment]
Yeah, I realized that after I read what it did, erp! Thanks for the clarification.

**Comment by ahedhi** [comment]
Done
