### ISSUE TITLE
Review the Pump Station Class name

### ISSUE THREAD

**Issue by collinsfoobar** [besasm/EMGAATS#86]
I believe the PumpStations class should be called the Pumps class.  If we were to implement a pump stations class this would be a collection of Pumps - among other things. I believe that we will treat pump stations similar to inflow controls - as node decorations.

Arnel, please review and let me know what you think.  If you'd like, reassign to me (collinsfoobar) and I will take care of it.

**Comment by arnelmandilag** [comment]
Go ahead and rename the class to Pump, and the table schema to Pumps.
