### ISSUE TITLE
Modify python script to match updated (6/4/2015) schema.  Import weirs and orifices.

### ISSUE THREAD

**Issue by collinsfoobar** [besasm/EMGAATS#94]
The add-in has been deployed with 6/4/2015 date and placed into:V:\9ESEN0000008\EMGAATS\ArcMapAddIn.

The following manually modified gdb loads properly:
V:\9ESEN0000008\EMGAATS\TestDataActive\ALderBasinTest4.gdb 

The following has updated weirs and orifices reflecting current schema
V:\9ESEN0000008\EMGAATS\DataSchema\EmgaatsTabularData.mdb

**Comment by ahedhi** [comment]
Has this been completed?
