### ISSUE TITLE
Figure out the details of the model class

### ISSUE THREAD

**Issue by collinsfoobar** [besasm/EMGAATS#95]
Model Work Flow
1. create model 
2. fill network 
3. edit network 
4. create simulation 
5 add boundary conditions
6. deploy to engine
7. run engine
8. extract and post process results (should these be stored in the simulation class?)
9. map results (determine connection between simulation and network)
10. Develop alternative
11. Run cost estimate

Will the model be used as the basis for editing master data

Other process notes
A new model is created for the following:
i.  Develop alternatives
ii. Edit master data

-> Cost estimates are only run on an alternative.

Working assumptions: 
A. Simulations and Network are owned by the model.
B. Simulations persist (we save simulations to file)  

if we go backwards in the workflow do we purge dependent steps.  For example once simulations are created (step 4) can we go back to step 3 and do more edits?  If so should we purge simulation collections?

What is controlled by gui and what is controlled by class?
For example if a new (or revised) network is added to a model, does set Network class purge simulations?

If a user decides to go to step 4 then the network could be locked.  If the user decides to unlock and edit then (after big warning) simulations get purged.

White board photo at link below.
![model_network_simulation_relationship](https://cloud.githubusercontent.com/assets/12415719/7997579/490f9898-0ae4-11e5-9ce6-abfbe2c9d0b6.JPG)

**Comment by arnelmandilag** [comment]
More thoughts to ponder:

- Something would have to initiate setting the one Network of a Model after the initial trace: retrace? user request? I don't think we currently support multiple Networks in a Model.
- When a user traces, we have a model. If a user edits that model, we essentially have an alternative. A user can add a simulation to a model/alternative at any time. During the course of editing an alternative, boundary conditions in the alternative's simulations could become orphaned or not current. I see no reason to purge simulations if an edit occurs afterwards.
